version: '3'

services:
  docker-mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tasker_database
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/tasker_database?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql
